/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import exe.*;
import com.*;
import db.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
//import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author userPC
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    int i;
    
    public AdminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_pelanggan = new javax.swing.JButton();
        jButton_kamar = new javax.swing.JButton();
        jButton_staff = new javax.swing.JButton();
        jButton_transaksi = new javax.swing.JButton();
        jButton_Insert = new javax.swing.JButton();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Baris1 = new javax.swing.JTextField();
        jTextField_Baris2 = new javax.swing.JTextField();
        jTextField_Baris3 = new javax.swing.JTextField();
        jTextField_Baris6 = new javax.swing.JTextField();
        jTextField_Baris7 = new javax.swing.JTextField();
        jTextField_Baris5 = new javax.swing.JTextField();
        jTextField_Baris4 = new javax.swing.JTextField();
        jButton_jenisKamar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_Data);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DATA MASTER");

        jButton_pelanggan.setText("Pelanggan");
        jButton_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pelangganActionPerformed(evt);
            }
        });

        jButton_kamar.setText("Kamar");
        jButton_kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kamarActionPerformed(evt);
            }
        });

        jButton_staff.setText("Staff");
        jButton_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_staffActionPerformed(evt);
            }
        });

        jButton_transaksi.setText("Transaksi");
        jButton_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_transaksiActionPerformed(evt);
            }
        });

        jButton_Insert.setText("Insert");
        jButton_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InsertActionPerformed(evt);
            }
        });

        jButton_Update.setText("Update");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Baris 2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Baris 3");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Baris 6");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Baris 4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Baris 5");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Baris 7");

        jTextField_Baris3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Baris3ActionPerformed(evt);
            }
        });

        jButton_jenisKamar.setText("Jenis Kamar");
        jButton_jenisKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_jenisKamarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_Baris1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Baris2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_Baris4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Baris5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Baris3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_Baris6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextField_Baris7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 292, Short.MAX_VALUE)
                                                        .addComponent(jButton_pelanggan)
                                                        .addGap(35, 35, 35)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_jenisKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_jenisKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_Baris1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Baris2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Baris3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Baris6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Baris7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Baris5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Baris4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InsertActionPerformed
        switch(i){
            case 1:
                Pelanggan newP = new Pelanggan();
                newP.setNamapelanggan(jTextField_Baris2.getText());
                newP.setAlamatpelanggan(jTextField_Baris3.getText());
                newP.setNoktp(Integer.parseInt(jTextField_Baris4.getText().replaceAll(",", "")));
                
                ExecutePelanggan exeP = new ExecutePelanggan();
                int Hasil = exeP.insertPelanggan(newP);
                JOptionPane.showMessageDialog(rootPane, Hasil);
                displayAllPelanggan();
                break;
            case 2:
                Kamar newK = new Kamar();
                newK.setIdjeniskamar(Integer.parseInt(jTextField_Baris2.getText().replaceAll(",", "")));
                newK.setNokamar(jTextField_Baris3.getText());
                newK.setStatus(jTextField_Baris4.getText());
                
                ExecuteKamar exeK = new ExecuteKamar();
                int h = exeK.insertkamar(newK);
                JOptionPane.showMessageDialog(rootPane, h);
                displayAllKamar();
                break;
            case 3:
                JenisKamar newJ = new JenisKamar();
                newJ.setHargakamar(Integer.parseInt(jTextField_Baris3.getText().replaceAll(",", "")));
                newJ.setKelaskamar(jTextField_Baris2.getText());
                newJ.setIsikamar(Integer.parseInt(jTextField_Baris4.getText().replaceAll(",", "")));
                
                ExecuteJenisKamar exeJ = new ExecuteJenisKamar();
                int Ha = exeJ.insertJenis(newJ);
                JOptionPane.showMessageDialog(rootPane, Ha);
                displayAllJenisKamar();
                break;
            case 4:
                Staff newS = new Staff();
                newS.setNamastaff(jTextField_Baris2.getText());
                
                ExecuteStaff exeS = new ExecuteStaff();
                int Has = exeS.insertStaff(newS);
                JOptionPane.showMessageDialog(rootPane, Has);
                displayAllStaff();
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Tabel");
                        
        }
    }//GEN-LAST:event_jButton_InsertActionPerformed

    private void jButton_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pelangganActionPerformed
        displayAllPelanggan();
        i = 1;
    }//GEN-LAST:event_jButton_pelangganActionPerformed

    private void jButton_kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kamarActionPerformed
        displayAllKamar();
        i = 2;
    }//GEN-LAST:event_jButton_kamarActionPerformed

    private void jButton_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_transaksiActionPerformed
        displayAllTransaksi();
    }//GEN-LAST:event_jButton_transaksiActionPerformed

    private void jButton_jenisKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_jenisKamarActionPerformed
        displayAllJenisKamar();
        i = 3;
    }//GEN-LAST:event_jButton_jenisKamarActionPerformed

    private void jButton_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_staffActionPerformed
        displayAllStaff();
        i = 4;
    }//GEN-LAST:event_jButton_staffActionPerformed

    private void jTextField_Baris3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Baris3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Baris3ActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        switch(i){
            case 1:
                Pelanggan newP = new Pelanggan();
                newP.setNamapelanggan(jTextField_Baris2.getText());
                newP.setAlamatpelanggan(jTextField_Baris3.getText());
                newP.setNoktp(Integer.parseInt(jTextField_Baris4.getText().replaceAll(",", "")));
                newP.setIdpelanggan(Integer.parseInt(jTextField_Baris1.getText().replaceAll(",", "")));
                
                ExecutePelanggan exeP = new ExecutePelanggan();
                int Hasil = exeP.updatePelanggan(newP);
                JOptionPane.showMessageDialog(rootPane, Hasil);
                displayAllPelanggan();
                break;
            case 2:
                Kamar newK = new Kamar();
                newK.setIdjeniskamar(Integer.parseInt(jTextField_Baris2.getText().replaceAll(",", "")));
                newK.setNokamar(jTextField_Baris3.getText());
                newK.setStatus(jTextField_Baris4.getText());
                newK.setIdkamar(Integer.parseInt(jTextField_Baris1.getText().replaceAll(",", "")));
                
                ExecuteKamar exeK = new ExecuteKamar();
                int h = exeK.updateKamar(newK);
                JOptionPane.showMessageDialog(rootPane, h);
                displayAllKamar();
                break;
            case 3:
                JenisKamar newJ = new JenisKamar();
                newJ.setHargakamar(Integer.parseInt(jTextField_Baris3.getText().replaceAll(",", "")));
                newJ.setKelaskamar(jTextField_Baris2.getText());
                newJ.setIsikamar(Integer.parseInt(jTextField_Baris4.getText().replaceAll(",", "")));
                newJ.setIdjeniskamar(Integer.parseInt(jTextField_Baris1.getText().replaceAll(",", "")));
                
                ExecuteJenisKamar exeJ = new ExecuteJenisKamar();
                int Ha = exeJ.updateJenis(newJ);
                JOptionPane.showMessageDialog(rootPane, Ha);
                displayAllJenisKamar();
                break;
            case 4:
                Staff newS = new Staff();
                newS.setNamastaff(jTextField_Baris2.getText());
                newS.setIdstaff(Integer.parseInt(jTextField_Baris1.getText().replaceAll(",", "")));
                
                ExecuteStaff exeS = new ExecuteStaff();
                int Has = exeS.updateJenis(newS);
                JOptionPane.showMessageDialog(rootPane, Has);
                displayAllStaff();
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Tabel");
        }
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        switch(i){
            case 1:
                ExecutePelanggan exeP = new ExecutePelanggan();
                int Hasil = exeP.deletePelanggan(jTextField_Baris1.getText());
                JOptionPane.showMessageDialog(rootPane, Hasil);
                displayAllPelanggan();
                break;
            case 2:
                ExecuteKamar exeK = new ExecuteKamar();
                int h = exeK.deleteKamar(jTextField_Baris1.getText());
                JOptionPane.showMessageDialog(rootPane, h);
                displayAllKamar();
                break;
            case 3:
                ExecuteJenisKamar exeJ = new ExecuteJenisKamar();
                int Ha = exeJ.deleteJenis(jTextField_Baris1.getText());
                JOptionPane.showMessageDialog(rootPane, Ha);
                displayAllJenisKamar();
                break;
            case 4:
                ExecuteStaff exeS = new ExecuteStaff();
                int Has = exeS.deleteStaff(jTextField_Baris1.getText());
                JOptionPane.showMessageDialog(rootPane, Has);
                displayAllStaff();
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Tabel");
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void displayAllStaff(){
            ExecuteStaff Staffs = new ExecuteStaff();
            Object[][] myKamar = Staffs.listStaff();
            tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
                    myKamar, 
                    new String[]{
                        "Id Staff", "Nama Staff"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, 
                    java.lang.String.class, java.lang.String.class,java.lang.String.class,java.lang.String.class
                };

                @Override
                public Class getColumnClass(int columnIndex){
                    return types [columnIndex];
                }
            });
        }
    
    private void displayAllJenisKamar(){
            ExecuteJenisKamar jnsKamr = new ExecuteJenisKamar();
            Object[][] myKamar = jnsKamr.listJenis();
            tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
                    myKamar, 
                    new String[]{
                        "Id Jenis Kamar", "Kelas Kamar", "Isi Kamar", "Harga Kamar"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, 
                    java.lang.String.class, java.lang.String.class,java.lang.String.class,java.lang.String.class
                };

                @Override
                public Class getColumnClass(int columnIndex){
                    return types [columnIndex];
                }
            });
        }
    
    private void displayAllPelanggan(){
            ExecutePelanggan plngn = new ExecutePelanggan();
            Object[][] myKamar = plngn.listPelanggan();
            tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
                    myKamar, 
                    new String[]{
                        "Id Pelanggan", "Nama Pelanggan", "Alamat", "No KTP"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, 
                    java.lang.String.class, java.lang.String.class,java.lang.String.class,java.lang.String.class
                };

                @Override
                public Class getColumnClass(int columnIndex){
                    return types [columnIndex];
                }
            });
        }
    
     private void displayAllKamar(){
            ExecuteKamar kmr = new ExecuteKamar();
            Object[][] myKamar = kmr.listKamar();
            tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
                    myKamar, 
                    new String[]{
                        "Id Kamar", "No Kamar", "Status", "Kelas", "Harga", "Isi"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, 
                    java.lang.String.class, java.lang.String.class,java.lang.String.class,java.lang.String.class
                };

                @Override
                public Class getColumnClass(int columnIndex){
                    return types [columnIndex];
                }
            });
        }
    private void displayAllTransaksi(){
            ExecuteTransaksi trans = new ExecuteTransaksi();
            Object[][] myTransaksi = trans.listTransaksi();
            tbl_Data.setModel(new javax.swing.table.DefaultTableModel(
                    myTransaksi, 
                    new String[]{                        
                        "Id Transaksi", "Nama Pelanggan", "No Kamar", "Total Harga",
                        "Tanggal Transaksi", "Check In", "Check Out"
                    }
            ) {
                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, 
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
                };

                @Override
                public Class getColumnClass(int columnIndex){
                    return types [columnIndex];
                }
            });
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Insert;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JButton jButton_jenisKamar;
    private javax.swing.JButton jButton_kamar;
    private javax.swing.JButton jButton_pelanggan;
    private javax.swing.JButton jButton_staff;
    private javax.swing.JButton jButton_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Baris1;
    private javax.swing.JTextField jTextField_Baris2;
    private javax.swing.JTextField jTextField_Baris3;
    private javax.swing.JTextField jTextField_Baris4;
    private javax.swing.JTextField jTextField_Baris5;
    private javax.swing.JTextField jTextField_Baris6;
    private javax.swing.JTextField jTextField_Baris7;
    private javax.swing.JTable tbl_Data;
    // End of variables declaration//GEN-END:variables
}
